[package]
name = "downloadmanager"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
env_logger ="0.11.4"
notify = "7.0.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.8"
toml = "0.8.19"
